 version: 2

 build:
   os: "ubuntu-24.04"
   tools:
     python: "3"
   jobs:

python:
  install:
    - method: pip
      path: "."
      extra_requirements:
        - docs
mkdocs:
   configuration: mkdocs.yml
