site_name: "RSVP"

nav:
  - api.md

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
          docstring_section_style: list
          merge_init_into_class: true
